import { getBlogListingTemplate } from "./blog-listing.template.js";
import { getBlogPostTemplate } from "./blog-post.template.js";
import { getQueriesTemplate } from "./queries.template.js";
import { getAdapterConfigTemplate } from "./adapter-config.template.js";
import { getApiRouteTemplate } from "./api-route.template.js";

export { getBlogListingTemplate } from "./blog-listing.template.js";
export { getBlogPostTemplate } from "./blog-post.template.js";
export { getQueriesTemplate } from "./queries.template.js";
export { getAdapterConfigTemplate } from "./adapter-config.template.js";
export { getApiRouteTemplate } from "./api-route.template.js";

/**
 * Complete manifest of files generated by `contlify init`.
 * Maps template getter to the target file path relative to the user's project root.
 */
export interface ScaffoldFileEntry {
  /** Relative path from project root where the file will be created. */
  relativePath: string;
  /** Function that returns the file content string. */
  getContent: () => string;
  /** Human-readable description for CLI output. */
  description: string;
}

/**
 * Returns the full list of files to scaffold during `contlify init`.
 */
export function getScaffoldManifest(): ScaffoldFileEntry[] {
  return [
    {
      relativePath: "app/api/contlify/[...path]/route.ts",
      getContent: getApiRouteTemplate,
      description: "API route handler (receives posts from publishers)",
    },
    {
      relativePath: "lib/contlify/adapter.ts",
      getContent: getAdapterConfigTemplate,
      description: "Database adapter configuration",
    },
    {
      relativePath: "lib/contlify/queries.ts",
      getContent: getQueriesTemplate,
      description: "Blog query functions (read-side)",
    },
    {
      relativePath: "app/blog/page.tsx",
      getContent: getBlogListingTemplate,
      description: "Blog listing page",
    },
    {
      relativePath: "app/blog/[slug]/page.tsx",
      getContent: getBlogPostTemplate,
      description: "Single blog post page",
    },
  ];
}
