/**
 * v2 template: server.contlify.ts
 * Angular SSR / Express gateway — generated by `npx contlify init`.
 *
 * Mounts the universal Contlify publishing handler onto Angular SSR's Express server.
 * All Contlify logic lives inside node_modules/contlify.
 * Configuration is resolved from contlify.config.ts via the active config cache.
 */
export function getAngularV2RouteTemplate(language: "ts" | "js" = "ts"): string {
  const isJs = language === "js";
  const expressImport = isJs ? "" : `\nimport type { Express } from "express";`;
  const appType = isJs ? `app` : `app: Express`;
  const voidReturn = isJs ? "" : ": void";
  const errCast = isJs ? `e` : `e: any`;

  return `import "./contlify.config";${expressImport}
import {
  createContlifyHandler,
  createNodeMiddleware,
  getAllPosts,
  getCategories,
  getPostBySlug,
  getPostsByCategory,
  getTags,
  getPostsByTag,
} from "contlify";

const contlifyHandler = createContlifyHandler();

/**
 * Mounts Contlify Publishing API & Public Read Routes onto the Angular SSR Express app.
 * Call this in server.ts before Angular's catch-all HTML rendering route.
 *
 * @example
 * \`\`\`ts
 * import { mountContlify } from "./server.contlify";
 * mountContlify(app);
 * \`\`\`
 */
export function mountContlify(${appType})${voidReturn} {
  // Public Read Routes for Client & SSR components
  app.get("/api/contlify/v1/posts", async (_req, res) => {
    try {
      const posts = await getAllPosts();
      res.json({ success: true, data: posts });
    } catch (${errCast}) {
      res.status(500).json({ success: false, error: e.message });
    }
  });

  app.get("/api/contlify/v1/posts/:slug", async (req, res) => {
    try {
      const post = await getPostBySlug(req.params.slug);
      if (!post) {
        res.status(404).json({ success: false, error: "Post not found" });
        return;
      }
      res.json({ success: true, data: post });
    } catch (${errCast}) {
      res.status(500).json({ success: false, error: e.message });
    }
  });

  app.get("/api/contlify/v1/categories", async (_req, res) => {
    try {
      const categories = await getCategories();
      res.json({ success: true, data: categories });
    } catch (${errCast}) {
      res.status(500).json({ success: false, error: e.message });
    }
  });

  app.get("/api/contlify/v1/categories/:slug", async (req, res) => {
    try {
      const posts = await getPostsByCategory(req.params.slug);
      res.json({ success: true, data: posts });
    } catch (${errCast}) {
      res.status(500).json({ success: false, error: e.message });
    }
  });

  app.get("/api/contlify/v1/tags", async (_req, res) => {
    try {
      const tags = await getTags();
      res.json({ success: true, data: tags });
    } catch (${errCast}) {
      res.status(500).json({ success: false, error: e.message });
    }
  });

  app.get("/api/contlify/v1/tags/:slug", async (req, res) => {
    try {
      const posts = await getPostsByTag(req.params.slug);
      res.json({ success: true, data: posts });
    } catch (${errCast}) {
      res.status(500).json({ success: false, error: e.message });
    }
  });

  // Publishing Gateway (POST /posts, PATCH /posts/:id, GET /validate, etc.)
  app.use("/api/contlify/v1", createNodeMiddleware(contlifyHandler));
}
`;
}
