/**
 * v2 template: src/pages/api/contlify/v1/[...path].ts
 * Thin Astro API endpoint gateway — generated by `npx contlify init`.
 *
 * This file only bridges Astro's file-system router to the Contlify library.
 * All Contlify logic lives inside node_modules/contlify.
 * Configuration is resolved from contlify.config.ts via the active config cache.
 */
export function getAstroV2RouteTemplate(): string {
  return `export const prerender = false;

import "../../../../../contlify.config";
import type { APIRoute } from "astro";
import { createContlifyHandler } from "contlify";

const handler = createContlifyHandler();

/**
 * Dispatch all HTTP methods to the Contlify handler.
 * For Cloudflare D1: bindContlifyEnv(context.locals.runtime?.env) before dispatching.
 */
export const ALL: APIRoute = async (context) => {
  return handler(context.request);
};

export const GET = ALL;
export const POST = ALL;
export const PATCH = ALL;
export const PUT = ALL;
export const DELETE = ALL;
export const OPTIONS = ALL;
export const HEAD = ALL;
`;
}
