/**
 * v2 template: src/pages/api/contlify/v1/[...path].ts  (or .js)
 * Thin Astro API endpoint gateway — generated by `npx contlify init`.
 *
 * This file only bridges Astro's file-system router to the Contlify library.
 * All Contlify logic lives inside node_modules/contlify.
 * Configuration is resolved from contlify.config.ts via the active config cache.
 */
export function getAstroV2RouteTemplate(language: "ts" | "js" = "ts"): string {
  const isJs = language === "js";
  const typeImport = isJs ? "" : `\nimport type { APIRoute } from "astro";`;
  const handlerType = isJs ? "" : `: APIRoute`;

  return `export const prerender = false;

import "../../../../../contlify.config";${typeImport}
import { createContlifyHandler } from "contlify";

const handler = createContlifyHandler();

export const ALL${handlerType} = async (context) => {
  try {
    // @ts-ignore
    process.loadEnvFile?.();
    // @ts-ignore
    process.loadEnvFile?.(".env.local");
  } catch {}
  try {
    const runtimeEnv = (context.locals${isJs ? "" : " as any"})?.runtime?.env;
    if (runtimeEnv) {
      if (typeof process !== "undefined" && process.env) {
        Object.assign(process.env, runtimeEnv);
      }
      Object.assign(globalThis, runtimeEnv);
    }
  } catch {}
  return handler(context.request);
};

export const GET = ALL;
export const POST = ALL;
export const PATCH = ALL;
export const PUT = ALL;
export const DELETE = ALL;
export const OPTIONS = ALL;
export const HEAD = ALL;
`;
}

