/**
 * v2 template: app/api/contlify/v1/[...path]/route.ts
 * Thin Next.js App Router gateway — generated by `npx contlify init`.
 *
 * This file only bridges Next.js's file-system router to the Contlify library.
 * All Contlify logic lives inside node_modules/contlify.
 * Configuration is resolved from contlify.config.ts via the active config cache.
 */
export function getNextjsV2RouteTemplate(baseDir: string = "src"): string {
  const importPath = baseDir === "src"
    ? `import "../../../../../../contlify.config";`
    : `import "../../../../../contlify.config";`;

  return `${importPath}
import { createNextHandler } from "contlify/next";

export const dynamic = "force-dynamic";

const handler = createNextHandler();

export {
  handler as GET,
  handler as POST,
  handler as PATCH,
  handler as PUT,
  handler as DELETE,
  handler as OPTIONS,
  handler as HEAD,
};
`;
}
