/**
 * v2 template: app/routes/api.contlify.$.ts  (or .js)
 * Thin React Router v7 catch-all gateway — generated by `npx contlify init`.
 *
 * This file only bridges React Router's file-system router to the Contlify library.
 * All Contlify logic lives inside node_modules/contlify.
 * Configuration is resolved from contlify.config.ts via the active config cache.
 */
export function getReactRouterV2RouteTemplate(language: "ts" | "js" = "ts"): string {
  const isJs = language === "js";
  const typeImport = isJs
    ? ""
    : `\nimport type { LoaderFunctionArgs, ActionFunctionArgs } from "react-router";`;
  const loaderArg = isJs ? `{ request, context }` : `{ request, context }: LoaderFunctionArgs`;
  const actionArg  = isJs ? `{ request, context }` : `{ request, context }: ActionFunctionArgs`;

  return `import "../../contlify.config";${typeImport}
import { createContlifyHandler } from "contlify";

const handler = createContlifyHandler();

// React Router v7 uses Cloudflare's module Worker format where D1/KV/R2 bindings
// are passed per-request as context.cloudflare.env — they are NOT on globalThis.
// Patching them onto globalThis lets createD1Adapter's env scan find the D1
// binding automatically, regardless of what it is named in wrangler.jsonc.
function patchCloudflareEnv(context) {
  const env = context?.cloudflare?.env ?? context?.env;
  if (env && typeof env === "object") {
    Object.assign(globalThis, env);
  }
}

export const loader = async (${loaderArg}) => {
  patchCloudflareEnv(context);
  return handler(request);
};

export const action = async (${actionArg}) => {
  patchCloudflareEnv(context);
  return handler(request);
};
`;
}

