/**
 * v2 template: app/routes/api.contlify.$.ts
 * Thin React Router v7 catch-all gateway — generated by `npx contlify init`.
 *
 * This file only bridges React Router's file-system router to the Contlify library.
 * All Contlify logic lives inside node_modules/contlify.
 * Configuration is resolved from contlify.config.ts via the active config cache.
 */
export function getReactRouterV2RouteTemplate(): string {
  return `import "../../contlify.config";
import type { LoaderFunctionArgs, ActionFunctionArgs } from "react-router";
import { createContlifyHandler } from "contlify";

const handler = createContlifyHandler();

export const loader = async ({ request }: LoaderFunctionArgs) => {
  return handler(request);
};

export const action = async ({ request }: ActionFunctionArgs) => {
  return handler(request);
};
`;
}
